version: 2
# enable-beta-ecosystems: true
updates:
  - package-ecosystem: "nuget"
    directory: "/console"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
  - package-ecosystem: "gomod"
    directory: "/templates/Go"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    labels:
      - "infrastructure"
      - "dependencies"
