version: 2
# enable-beta-ecosystems: true
updates:
  - package-ecosystem: "nuget"
    directory: "/console"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "tr*"
        update-types: ["version-update:semver-patch"]
     labels:
      - "infrastructure"
      - "dependencies"
  - package-ecosystem: gomod
    directory: "/templates/Go"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
