version: 2
updates:
  # dotnet tools
  - package-ecosystem: "nuget"
    directory: "/_scripts/templates/CSharp"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
  # dotnet tools
  - package-ecosystem: "npm"
    directory: "/_scripts/templates/TypeScript"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
        # dotnet tools
  - package-ecosystem: "npmt"
    directory: "/_scripts/templates/JavaScript"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
