version: 2
# enable-beta-ecosystems: true
updates:
  - package-ecosystem: "nuget"
    directory: "/console"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
